// Code generated by command: go run f1600x4_amd64_src.go -out f1600x4_amd64.s -stubs f1600x4_amd64_stubs.go. DO NOT EDIT.

//go:build amd64
// +build amd64

package f1600x4

//go:noescape
func f1600x4(state *uint64, rc *[24]uint64)
